// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBg27bVcueFBEYake7bKH3xWGbGEx49Xg',
    appId: '1:291636949592:web:315aa6fcaf7a57a1db902d',
    messagingSenderId: '291636949592',
    projectId: 'kaiteki-bfdf5',
    authDomain: 'kaiteki-bfdf5.firebaseapp.com',
    storageBucket: 'kaiteki-bfdf5.appspot.com',
    measurementId: 'G-DWSWLS5YLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuOKmdEofzE3rJEOMTQJWWwfnddPq81k4',
    appId: '1:291636949592:android:0fd854ded88f1740db902d',
    messagingSenderId: '291636949592',
    projectId: 'kaiteki-bfdf5',
    storageBucket: 'kaiteki-bfdf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmcNUXEwvFkXEuhB5_8e3PjKZQ9Eev0Yo',
    appId: '1:291636949592:ios:1f156ce429598527db902d',
    messagingSenderId: '291636949592',
    projectId: 'kaiteki-bfdf5',
    storageBucket: 'kaiteki-bfdf5.appspot.com',
    iosBundleId: 'com.example.kite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmcNUXEwvFkXEuhB5_8e3PjKZQ9Eev0Yo',
    appId: '1:291636949592:ios:1f156ce429598527db902d',
    messagingSenderId: '291636949592',
    projectId: 'kaiteki-bfdf5',
    storageBucket: 'kaiteki-bfdf5.appspot.com',
    iosBundleId: 'com.example.kite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBg27bVcueFBEYake7bKH3xWGbGEx49Xg',
    appId: '1:291636949592:web:4af91a0b89e49ed5db902d',
    messagingSenderId: '291636949592',
    projectId: 'kaiteki-bfdf5',
    authDomain: 'kaiteki-bfdf5.firebaseapp.com',
    storageBucket: 'kaiteki-bfdf5.appspot.com',
    measurementId: 'G-604LRE7BB1',
  );
}
